#
# Copyright (c) 2006-2015 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        cookie_phishing:
            enable: true
            autorun: true
            category: "Social Engineering"
            name: "Cookie Phishing"
            description: "This plugin grabs the cookie of the hooked website as well as the password if they enter it"
            authors: ["Anthony Midora Dillon"]
            target:
                user_notify: ['ALL']
